### ISSUE TITLE
[Bug]: BRNT3DOOMSDAY Side turret misalignment issue when firing

### ISSUE THREAD

**Issue by zhanghm18GIT** [FAForever/fa-total-mayhem#15]
### What happened?

The first time a new BRNT3DOOMSDAY fires an attack, the small turrets on his sides will slide a short distance like the side.

### Steps to reproduce

All you have to do is cheat a BRNT3DOOMSDAY and have him attack the ground and you'll be able to spot the unusual behavior of the small turrets on either side of him

### Expected behavior

I checked the scm and scan files and found the problem. The small turret bone position in SCA is different from that in scm. This causes the four turrets in the red circle to be misaligned every time the unit plays the sca animation (i.e. the animation of opening the missile launcher).
If someone can make the small turret position in the sca file of this unit match that in the scm file, the problem should be solved. I personally think the position of the turret is correct in scm, because it looks like the turret's rotating axis is right in the center of the base circle, while the turret's position is obviously off in sca.

**Comment by zhanghm18GIT** [comment]
![a63cc2f46e7dfedf](https://github.com/FAForever/fa-total-mayhem/assets/142378820/aa1f42a5-0e7c-451d-98d5-c1913db7f271)
Additional image: The turret in the red circle in the image is the turret with the problem. You can see that these turrets are positioned differently in SCA and scm

**Comment by Uveso** [comment]
Well, if you delete the BRNT3DOOMSDAY_Deploy.sca file, the turret animation works correctly.
That leads me to the conclusion that the error is indeed in the .sca file.
Unfortunately, I can't change the animation file. :(

**Comment by zhanghm18GIT** [comment]
> Well, if you delete the BRNT3DOOMSDAY_Deploy.sca file, the turret animation works correctly. That leads me to the conclusion that the error is indeed in the .sca file. Unfortunately, I can't change the animation file. :(

Sad. Hopefully someone will help solve this problem later

**Comment by Uveso** [comment]
I am already talking to a guy who should be able to solve this. :)
At least there is hope hehe

**Comment by Uveso** [comment]
fixed https://github.com/FAForever/fa-total-mayhem/pull/29
