### ISSUE TITLE
[Bug]: BRPT3SHBM:The unit muzzle does not rotate with the turret of the upper body

### ISSUE THREAD

**Issue by zhanghm18GIT** [FAForever/fa-total-mayhem#16]
### What happened?

There seems to be a problem with one unit model in TOTALMAYHEM. The unit's muzzle position does not move as the turret rotates, causing the laser to shoot from the wrong position when the turret rotates
![图片](https://github.com/FAForever/fa-total-mayhem/assets/142378820/612410c7-f499-4ea0-b58d-5d9de8c24059)
![图片](https://github.com/FAForever/fa-total-mayhem/assets/142378820/434ef704-01f6-4614-8839-7ab9f662b8da)

### Steps to reproduce

Have this unit fire to the left, right, and right, and you'll see problems with the laser beam and the muzzle.

### Expected behavior

I have fixed this problem by editing the scm file. But I don't know how to operate PR on github. That's why I sent the file I fixed here. If there is no p
[BRPT3SHBM_lod0.zip](https://github.com/user-attachments/files/15858478/BRPT3SHBM_lod0.zip)
roblem after anyone checks, he can directly adopt.

**Comment by Uveso** [comment]
fixed in https://github.com/FAForever/fa-total-mayhem/pull/27
