### ISSUE TITLE
[Bug]: BROT1BT and BROT1BTT2 cannot travel forward properly

### ISSUE THREAD

**Issue by zhanghm18GIT** [FAForever/fa-total-mayhem#43]
### What happened?

- AEON's T1battle tanks, BROT1BT and BROT1BTT2, will only walk backwards, not forwards, when ordered to move

### Steps to reproduce

Just command the two units to move, and you'll see that they can only drive backwards

### Expected behavior

When a tank moves, the front of the tank should face forward

**Comment by Uveso** [comment]
I tested the units. But obviously, I only let them move a few meters, and that was short enough for them to drive backward :D
I'll ask Saver again if he can fix that for us.
